# Generated by Django 5.1.7 on 2025-03-18 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='couple_fee',
            new_name='seat_fee',
        ),
        migrations.RenameField(
            model_name='eventbooking',
            old_name='couple_count',
            new_name='seat_count',
        ),
        migrations.RemoveField(
            model_name='event',
            name='max_couple_bookings',
        ),
        migrations.RemoveField(
            model_name='event',
            name='max_stag_bookings',
        ),
        migrations.RemoveField(
            model_name='event',
            name='stag_fee',
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='stag_count',
        ),
    ]
