# Generated by Django 5.1.7 on 2025-03-18 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_couple_fee_event_seat_fee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='seat_fee',
            new_name='couple_fee',
        ),
        migrations.AddField(
            model_name='event',
            name='stag_fee',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='ticket_type',
            field=models.CharField(choices=[('STAG', 'Stag'), ('COUPLE', 'Couple')], default='STAG', max_length=10),
            preserve_default=False,
        ),
    ]
