# Generated by Django 5.1.7 on 2025-03-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_seat_fee_event_couple_fee_event_stag_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='couple_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='stag_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
